const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Anchor,
		C3.Behaviors.solid,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.bound,
		C3.Behaviors.Flash,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Plugins.Text,
		C3.Behaviors.Timer,
		C3.Plugins.Spritefont2,
		C3.Behaviors.jumpthru,
		C3.Behaviors.Bullet,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Behaviors.Timer.Cnds.IsTimerRunning,
		C3.Behaviors.Timer.Exps.Duration,
		C3.Behaviors.Timer.Exps.CurrentTime,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.Flash.Acts.Flash,
		C3.ScriptsInEvents.EventosJogo_Event22_Act1,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Sprite.Cnds.CompareZElevation,
		C3.Behaviors.Timer.Acts.StopTimer,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion
	];
};
self.C3_JsPropNameTable = [
	{Âncora: 0},
	{background: 0},
	{Sólido: 0},
	{ground: 0},
	{cod: 0},
	{Plataforma: 0},
	{CentrarEm: 0},
	{RestritoAoLayout: 0},
	{Piscar: 0},
	{dev: 0},
	{Teclado: 0},
	{Mouse: 0},
	{Áudio: 0},
	{codtxt: 0},
	{qtcod: 0},
	{Cronômetro: 0},
	{relogio: 0},
	{placa: 0},
	{placa2: 0},
	{timer: 0},
	{arteMenu: 0},
	{menu: 0},
	{titulo: 0},
	{jogar: 0},
	{tutorial: 0},
	{direcao: 0},
	{cliente: 0},
	{PularAtravés: 0},
	{ground2: 0},
	{limite: 0},
	{pc: 0},
	{cadeira: 0},
	{planta: 0},
	{bebedouro: 0},
	{cafeteira: 0},
	{mesa: 0},
	{commit: 0},
	{Sprite: 0},
	{vitoria: 0},
	{Sprite2: 0},
	{irMenu: 0},
	{tutorialTxt1: 0},
	{tutorialTxt2: 0},
	{tutorialTxt3: 0},
	{tutorialTxt4: 0},
	{tutorialTxt5: 0},
	{irCreditos: 0},
	{Sprite3: 0},
	{Projétil: 0},
	{creditos: 0},
	{voltar: 0},
	{tutorialTxt6: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{FonteDeSprites: 0},
	{cod2: 0},
	{codigos: 0},
	{codigosNecessarios: 0}
];

self.InstanceType = {
	background: class extends self.ISpriteInstance {},
	ground: class extends self.ISpriteInstance {},
	cod: class extends self.ISpriteInstance {},
	dev: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Áudio: class extends self.IInstance {},
	codtxt: class extends self.ISpriteInstance {},
	qtcod: class extends self.ITextInstance {},
	relogio: class extends self.ISpriteInstance {},
	placa: class extends self.ISpriteInstance {},
	placa2: class extends self.ISpriteInstance {},
	timer: class extends self.ITextInstance {},
	arteMenu: class extends self.ISpriteInstance {},
	menu: class extends self.ISpriteInstance {},
	titulo: class extends self.ISpriteFontInstance {},
	jogar: class extends self.ISpriteFontInstance {},
	tutorial: class extends self.ISpriteFontInstance {},
	cliente: class extends self.ISpriteInstance {},
	ground2: class extends self.ISpriteInstance {},
	limite: class extends self.ISpriteInstance {},
	pc: class extends self.ISpriteInstance {},
	cadeira: class extends self.ISpriteInstance {},
	planta: class extends self.ISpriteInstance {},
	bebedouro: class extends self.ISpriteInstance {},
	cafeteira: class extends self.ISpriteInstance {},
	mesa: class extends self.ISpriteInstance {},
	commit: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	vitoria: class extends self.ISpriteFontInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	irMenu: class extends self.ISpriteFontInstance {},
	tutorialTxt1: class extends self.ISpriteFontInstance {},
	tutorialTxt2: class extends self.ISpriteFontInstance {},
	tutorialTxt3: class extends self.ISpriteFontInstance {},
	tutorialTxt4: class extends self.ISpriteFontInstance {},
	tutorialTxt5: class extends self.ISpriteFontInstance {},
	irCreditos: class extends self.ISpriteFontInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	creditos: class extends self.ITextInstance {},
	voltar: class extends self.ISpriteFontInstance {},
	tutorialTxt6: class extends self.ISpriteFontInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	FonteDeSprites: class extends self.ISpriteFontInstance {},
	cod2: class extends self.ISpriteInstance {}
}